version: '3.3'

services:

  mongo:
    image: mongo:4.0.28  
    restart: always
    container_name: mongo4028
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: mongo
    #   MONGO_INITDB_ROOT_PASSWORD: admintest
    ports:
      - "27017:27017"
    volumes:
         - "./data:/data/db"
      #      # - type: volume
      #      #   source: mongodb_data_volume
      #      #   target: /data/db
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.slaveOk().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
        
#   mongo-express:
#     image: mongo-express
#     container_name: mongo-express
#     restart: always
#     ports:
#       - "28081:8081"
#     environment:
#       ME_CONFIG_MONGODB_SERVER: mongo
#       ME_CONFIG_BASICAUTH_USERNAME: admin
#       ME_CONFIG_BASICAUTH_PASSWORD: changeme
#       #ME_CONFIG_MONGODB_AUTH_DATABASE: admin
#       ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
#       ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
#       ME_CONFIG_MONGODB_URL: mongo://mongoadmin:mongoadmin@mongo:27017/ 
#     depends_on:
#       - mongo

# volumes:
#   mongodb_data_volume:
#     driver: local
